# -*- coding: utf-8 -*-
"""DQLAB TETRIS4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16qwXA7n2YNwOn5nofEYFslk8h_eLtXn7
"""

#import library yang digunakan
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

#source = https://data.humdata.org/dataset/wfp-food-prices-for-indonesia?

path_dataset = "/content/drive/MyDrive/DQLAB Project/dataset/wfp_food_prices_idn (1).csv"

df= pd.read_csv(path_dataset)

df.tail()

df.info()

df.shape

df.head(5)

df.columns

df = df.drop(df.index[0:28101])

df.head(5)

df.commodity.unique()

df.isnull().sum()

df.drop(['latitude','longitude'], axis = 1, inplace=True)

df.dropna(inplace=True)

df.isnull().sum()

semarang = df[df['admin2'] == "KOTA SEMARANG"]

semarang

df['date'] =pd.to_datetime(df['date'])

df.info()

df['date']

semarang

df.drop(['admin1','market','category','unit','pricetype','currency'], axis = 1, inplace=True)

df.drop(['priceflag'], axis=1, inplace=True)

df.info()

df.loc[df['admin2']=='KOTA SEMARANG']

df.drop(['commodity'], axis=1, inplace=True)

df.drop(['admin2'], axis=1, inplace=True)

df.loc[28101:89834, 'price']

df['price']=df['price'].astype(float)
df['usdprice']=df['usdprice'].astype(float)

df

jan20 = df.loc[28101:33255, 'price']
mean_jan20 = jan20.mean()
jan20fix=mean_jan20.round(2)

feb20 = df.loc[33256:38399, 'price']
mean_feb20 = feb20.mean()
feb20fix=mean_feb20.round(2)

mar20 = df.loc[38400:43536, 'price']
mean_mar20 = mar20.mean()
mar20fix=mean_mar20.round(2)

apr20 = df.loc[43537:48666, 'price']
mean_apr20 = apr20.mean()
apr20fix=mean_apr20.round(2)

mei20 = df.loc[48667:53802, 'price']
mean_mei20 = mei20.mean()
mei20fix = mean_mei20.round(2)

####LANJUTT
jun20 = df.loc[53803:58944, 'price']
mean_jun20 = jun20.mean()
jun20fix = mean_jun20.round(2)

jul20 = df.loc[58945:64079, 'price']
mean_jul20 = jul20.mean()
jul20fix = mean_jul20.round(2)

aug20 = df.loc[64080:69198, 'price']
mean_aug20 = aug20.mean()
aug20fix = mean_aug20.round(2)

sep20 = df.loc[69199:74331, 'price']
mean_sep20 = sep20.mean()
sep20fix = mean_sep20.round(2)

oct20 = df.loc[74332:79461, 'price']
mean_oct20 = oct20.mean()
oct20fix = mean_oct20.round(2)

nov20 = df.loc[79462:84615, 'price']
mean_nov20 = nov20.mean()
nov20fix = mean_nov20.round(2)

nov20 = df.loc[79462:84615, 'price']
mean_nov20 = nov20.mean()
nov20fix = mean_nov20.round(2)

dec20 = df.loc[84616:89834, 'price']
mean_dec20 = dec20.mean()
dec20fix = mean_dec20.round(2)

###TEST VISUALISASI 2020 DENGAN KODE CARA BODOH

bulan1= ['jan','feb','mar','apr','mei','jun','jul','aug','sep','oct','nov','dec']
meanfix = [jan20fix, feb20fix, mar20fix, apr20fix, mei20fix, jun20fix, jul20fix, aug20fix, sep20fix, oct20fix, nov20fix, dec20fix]

sns.barplot(x=bulan1, y=meanfix)
plt.title('Bar Plot')
plt.xlabel('bulan 2020')
plt.ylabel('mean fix')
plt.show()

jan21 = df.loc[89835:95116, 'price']
mean_jan21 = jan21.mean()
jan21fix=mean_jan21.round(2)

feb21 = df.loc[95117:100430, 'price']
mean_feb21 = feb21.mean()
feb21fix=mean_feb21.round(2)

mar21 = df.loc[100431:105774, 'price']
mean_mar21 = mar21.mean()
mar21fix=mean_mar21.round(2)

apr21 = df.loc[105775:111145, 'price']
mean_apr21 = apr21.mean()
apr21fix=mean_apr21.round(2)

mei21 = df.loc[111146:116513, 'price']
mean_mei21 = mei21.mean()
mei21fix=mean_mei21.round(2)

jun21 = df.loc[116514:121868, 'price']
mean_jun21 = jun21.mean()
jun21fix=mean_jun21.round(2)

jul21 = df.loc[121869:127240, 'price']
mean_jul21 = jul21.mean()
jul21fix=mean_jul21.round(2)

aug21 = df.loc[127240:132616, 'price']
mean_aug21 = aug21.mean()
aug21fix=mean_aug21.round(2)

sep21 = df.loc[132617:138006, 'price']
mean_sep21 = sep21.mean()
sep21fix=mean_sep21.round(2)

oct21 = df.loc[138007:143406, 'price']
mean_oct21 = oct21.mean()
oct21fix=mean_oct21.round(2)

nov21 = df.loc[143407:148803, 'price']
mean_nov21 = nov21.mean()
nov21fix=mean_nov21.round(2)

dec21 = df.loc[148804:154190, 'price']
mean_dec21 = dec21.mean()
dec21fix=mean_dec21.round(2)

###TEST VISUALISASI 220 DENGAN KODE CARA BODOH

bulan1= ['jan','feb','mar','apr','mei','jun','jul','aug','sep','oct','nov','dec']
meanfix = [jan21fix, feb21fix, mar21fix, apr21fix, mei21fix, jun21fix, jul21fix, aug21fix, sep21fix, oct21fix, nov21fix, dec21fix]

sns.barplot(x=bulan1, y=meanfix)
plt.title('Bar Plot')
plt.xlabel('bulan 2021')
plt.ylabel('mean fix')
plt.show()

jan22 = df.loc[154191:159588, 'price']
mean_jan22 = jan22.mean()
jan22fix=mean_jan22.round(2)

feb22 = df.loc[159589:164992, 'price']
mean_feb22 = feb22.mean()
feb22fix=mean_feb22.round(2)

mar22 = df.loc[164993:170375, 'price']
mean_mar22 = mar22.mean()
mar22fix=mean_mar22.round(2)

apr22 = df.loc[170376:175771, 'price']
mean_apr22 = apr22.mean()
apr22fix=mean_apr22.round(2)

mei22 = df.loc[175772:181153, 'price']
mean_mei22 = mei22.mean()
mei22fix=mean_mei22.round(2)

jun22 = df.loc[181154:186536, 'price']
mean_jun22 = jun22.mean()
jun22fix=mean_jun22.round(2)

jul22 = df.loc[186537:191916, 'price']
mean_jul22 = jul22.mean()
jul22fix=mean_jul22.round(2)

aug22 = df.loc[191917:197303, 'price']
mean_aug22 = aug22.mean()
aug22fix=mean_aug22.round(2)

sep22 = df.loc[197304:202681, 'price']
mean_sep22 = sep22.mean()
sep22fix=mean_sep22.round(2)

oct22 = df.loc[202682:208059, 'price']
mean_oct22 = oct22.mean()
oct22fix=mean_oct22.round(2)

nov22 = df.loc[208060:213443, 'price']
mean_nov22 = nov22.mean()
nov22fix=mean_nov22.round(2)

dec22 = df.loc[213444:218813, 'price']
mean_dec22 = dec22.mean()
dec22fix=mean_dec22.round(2)

###TEST VISUALISASI 2020 DENGAN KODE CARA BODOH

bulan1= ['jan','feb','mar','apr','mei','jun','jul','aug','sep','oct','nov','dec']
meanfix = [jan22fix, feb22fix, mar22fix, apr22fix, mei22fix, jun22fix, jul22fix, aug22fix, sep22fix, oct22fix, nov22fix, dec22fix]

sns.barplot(x=bulan1, y=meanfix)
plt.title('Bar Plot')
plt.xlabel('bulan 2022')
plt.ylabel('mean fix')
plt.show()

jan23 = df.loc[218814:224200, 'price']
mean_jan23 = jan23.mean()
jan23fix=mean_jan23.round(2)

feb23 = df.loc[224201:229529, 'price']
mean_feb23 = feb23.mean()
feb23fix=mean_feb23.round(2)

mar23 = df.loc[229530:234875, 'price']
mean_mar23 = mar23.mean()
mar23fix=mean_mar23.round(2)

apr23 = df.loc[234876:240228, 'price']
mean_apr23 = apr23.mean()
apr23fix=mean_apr23.round(2)

mei23 = df.loc[240229:245586, 'price']
mean_mei23 = mei23.mean()
mei23fix=mean_mei23.round(2)

jun23 = df.loc[245587:250941, 'price']
mean_jun23 = jun23.mean()
jun23fix=mean_jun23.round(2)

jul23 = df.loc[250942:256007, 'price']
mean_jul23 = jul23.mean()
jul23fix=mean_jul23.round(2)

aug23 = df.loc[256008:261072, 'price']
mean_aug23 = aug23.mean()
aug23fix=mean_aug23.round(2)

sep23 = df.loc[261073:266141, 'price']
mean_sep23 = sep23.mean()
sep23fix=mean_sep23.round(2)

oct23 = df.loc[266142:271202, 'price']
mean_oct23 = oct23.mean()
oct23fix=mean_oct23.round(2)

nov23 = df.loc[271203:276264, 'price']
mean_nov23 = nov23.mean()
nov23fix=mean_nov23.round(2)

dec23 = df.loc[276265:281322, 'price']
mean_dec23 = dec23.mean()
dec23fix=mean_dec23.round(2)

###TEST VISUALISASI 2020 DENGAN KODE CARA BODOH

bulan1= ['jan','feb','mar','apr','mei','jun','jul','aug','sep','oct','nov','dec']
meanfix = [jan23fix, feb23fix, mar23fix, apr23fix, mei23fix, jun23fix, jul23fix, aug23fix, sep23fix, oct23fix, nov23fix, dec23fix]

sns.barplot(x=bulan1, y=meanfix)
plt.title('Bar Plot')
plt.xlabel('bulan 2023')
plt.ylabel('mean fix')
plt.show()

data2 = {
    'Bulan' : ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],
    '2020' : [37371.59, 38748.06, 36136.27, 35264.05, 34463.12, 33780.0, 32659.14, 32481.96, 31505.33, 33365.72, 34477.05, 37401.78],
    '2021' : [39053.01, 39315.35, 40083.93, 38657.12, 37007.57, 35124.02, 36308.77, 33972.07, 32910.91, 33780.25, 34668.28, 39214.37],
    '2022' : [37722.55, 36765.15, 39754.42, 39376.42, 40129.32, 46094.56, 48202.08, 42365.58, 41312.6, 38402.79, 36789.77, 38583.48],
    '2023' : [39896.95, 39934.25, 40714.74, 39051.44, 39277.27, 40138.4, 40108.23, 39473.5, 38212.05, 39701.11, 43723.42, 45258.49]
}

df2 = pd.DataFrame(data2)
df2 = df2.set_index('Bulan')

mean_dec23.round(2)

plt.figure(figsize=(12, 6))
sns.set_style("whitegrid")

for col in df2.columns:
    plt.plot(df2.index, df2[col], marker='o', label=col)

plt.title('Rerata Harga Pangan Pokok per Bulan (2020-2024)')
plt.xlabel('Bulan')
plt.ylabel('Harga')
plt.xticks(rotation=45)
plt.legend(title='Tahun')
plt.tight_layout()
plt.show()

mean_dec20.round(2)

##source : https://id.investing.com/currencies/usd-idr-historical-data

historis_usd = '/content/drive/MyDrive/DQLAB Project/dataset/Data Historis USD_IDR (2).csv'

df3 = pd.read_csv(historis_usd)

df3

df3.info()

df3.drop(['Pembukaan','Tertinggi','Terendah', 'Vol.', 'Perubahan%'], axis = 1, inplace=True)

df3.info()

df3.to_csv('historis usd clean.csv')

df3

df3 = df3.drop(df3.index[0:11])

df3.head(15)

df3 = df3.rename(columns={'Tanggal': 'time', 'Terakhir': 'idr'})

df3['idr'] = df3['idr'].str.slice(stop=-2)

df3.head(30)

df3['idr']=df3['idr'].astype(str)

df3['idr'] = df3['idr'].str.replace('.', '')

df3.head(30)

df3['idr']=df3['idr'].astype(float)

df3.head()

kurs_dec23 = df3.loc[11:31, 'idr']
mean_kurs_dec23 = kurs_dec23.mean()
mk_dec23 = mean_kurs_dec23.round(2)

mk_nov23

kurs_nov23 = df3.loc[32:53, 'idr']
mean_kurs_nov23 = kurs_nov23.mean()
mk_nov23 = mean_kurs_nov23.round(2)

kurs_oct23 = df3.loc[54:75, 'idr']
mean_kurs_oct23 = kurs_oct23.mean()
mk_oct23 = mean_kurs_oct23.round(2)

kurs_sep23 = df3.loc[76:96, 'idr']
mean_kurs_sep23 = kurs_sep23.mean()
mk_sep23 = mean_kurs_sep23.round(2)

kurs_aug23 = df3.loc[97:119, 'idr']
mean_kurs_aug23 = kurs_aug23.mean()
mk_aug23 = mean_kurs_aug23.round(2)

kurs_jul23 = df3.loc[120:140, 'idr']
mean_kurs_jul23 = kurs_jul23.mean()
mk_jul23 = mean_kurs_jul23.round(2)

kurs_jun23 = df3.loc[141:162, 'idr']
mean_kurs_jun23 = kurs_jun23.mean()
mk_jun23 = mean_kurs_jun23.round(2)

kurs_mei23 = df3.loc[163:184, 'idr']
mean_kurs_mei23 = kurs_mei23.mean()
mk_mei23 = mean_kurs_mei23.round(2)

kurs_apr23 = df3.loc[185:198, 'idr']
mean_kurs_apr23 = kurs_apr23.mean()
mk_apr23 = mean_kurs_apr23.round(2)

kurs_mar23 = df3.loc[199:219, 'idr']
mean_kurs_mar23 = kurs_mar23.mean()
mk_mar23 = mean_kurs_mar23.round(2)

kurs_feb23 = df3.loc[220:239, 'idr']
mean_kurs_feb23 = kurs_feb23.mean()
mk_feb23 = mean_kurs_feb23.round(2)

kurs_jan23 = df3.loc[240:260, 'idr']
mean_kurs_jan23 = kurs_jan23.mean()
mk_jan23 = mean_kurs_jan23.round(2)

kurs_dec22 = df3.loc[261:282, 'idr']
mean_kurs_dec22 = kurs_dec22.mean()
mk_dec22 = mean_kurs_dec22.round(2)

kurs_nov22 = df3.loc[282:304, 'idr']
mean_kurs_nov22 = kurs_nov22.mean()
mk_nov22 = mean_kurs_nov22.round(2)

kurs_oct22 = df3.loc[305:325, 'idr']
mean_kurs_oct22 = kurs_oct22.mean()
mk_oct22 = mean_kurs_oct22.round(2)

kurs_sep22 = df3.loc[326:347, 'idr']
mean_kurs_sep22 = kurs_sep22.mean()
mk_sep22 = mean_kurs_sep22.round(2)

kurs_aug22 = df3.loc[348:369, 'idr']
mean_kurs_aug22 = kurs_aug22.mean()
mk_aug22 = mean_kurs_aug22.round(2)

kurs_jul22 = df3.loc[370:390, 'idr']
mean_kurs_jul22 = kurs_jul22.mean()
mk_jul22 = mean_kurs_jul22.round(2)

kurs_jun22 = df3.loc[391:411, 'idr']
mean_kurs_jun22 = kurs_jun22.mean()
mk_jun22 = mean_kurs_jun22.round(2)

kurs_mei22 = df3.loc[412:426, 'idr']
mean_kurs_mei22 = kurs_mei22.mean()
mk_mei22 = mean_kurs_mei22.round(2)

kurs_apr22 = df3.loc[427:445, 'idr']
mean_kurs_apr22 = kurs_apr22.mean()
mk_apr22 = mean_kurs_apr22.round(2)

kurs_mar22 = df3.loc[446:467, 'idr']
mean_kurs_mar22 = kurs_mar22.mean()
mk_mar22 = mean_kurs_mar22.round(2)

kurs_feb22 = df3.loc[468:485, 'idr']
mean_kurs_feb22 = kurs_feb22.mean()
mk_feb22 = mean_kurs_feb22.round(2)

kurs_jan22 = df3.loc[486:506, 'idr']
mean_kurs_jan22 = kurs_jan22.mean()
mk_jan22 = mean_kurs_jan22.round(2)

kurs_dec21 = df3.loc[507:529, 'idr']
mean_kurs_dec21 = kurs_dec21.mean()
mk_dec21 = mean_kurs_dec21.round(2)

kurs_nov21 = df3.loc[530:551, 'idr']
mean_kurs_nov21 = kurs_nov21.mean()
mk_nov21 = mean_kurs_nov21.round(2)

kurs_oct21 = df3.loc[552:571, 'idr']
mean_kurs_oct21 = kurs_oct21.mean()
mk_oct21 = mean_kurs_oct21.round(2)

kurs_sep21 = df3.loc[572:593, 'idr']
mean_kurs_sep21 = kurs_sep21.mean()
mk_sep21 = mean_kurs_sep21.round(2)

kurs_aug21 = df3.loc[594:613, 'idr']
mean_kurs_aug21 = kurs_aug21.mean()
mk_aug21 = mean_kurs_aug21.round(2)

kurs_jul21 = df3.loc[614:634, 'idr']
mean_kurs_jul21 = kurs_jul21.mean()
mk_jul21 = mean_kurs_jul21.round(2)

kurs_jun21 = df3.loc[635:655, 'idr']
mean_kurs_jun21 = kurs_jun21.mean()
mk_jun21 = mean_kurs_jun21.round(2)

kurs_mei21 = df3.loc[656:672, 'idr']
mean_kurs_mei21 = kurs_mei21.mean()
mk_mei21 = mean_kurs_mei21.round(2)

kurs_apr21 = df3.loc[673:693, 'idr']
mean_kurs_apr21 = kurs_apr21.mean()
mk_apr21 = mean_kurs_apr21.round(2)

kurs_mar21 = df3.loc[694:715, 'idr']
mean_kurs_mar21 = kurs_mar21.mean()
mk_mar21 = mean_kurs_mar21.round(2)

kurs_feb21 = df3.loc[716:734, 'idr']
mean_kurs_feb21 = kurs_feb21.mean()
mk_feb21 = mean_kurs_feb21.round(2)

kurs_jan21 = df3.loc[735:755, 'idr']
mean_kurs_jan21 = kurs_jan21.mean()
mk_jan21 = mean_kurs_jan21.round(2)

kurs_dec20 = df3.loc[756:774, 'idr']
mean_kurs_dec20 = kurs_dec20.mean()
mk_dec20 = mean_kurs_dec20.round(2)

kurs_nov20 = df3.loc[775:795, 'idr']
mean_kurs_nov20 = kurs_nov20.mean()
mk_nov20 = mean_kurs_nov20.round(2)

kurs_oct20 = df3.loc[796:814, 'idr']
mean_kurs_oct20 = kurs_oct20.mean()
mk_oct20 = mean_kurs_oct20.round(2)

kurs_sep20 = df3.loc[815:836, 'idr']
mean_kurs_sep20 = kurs_sep20.mean()
mk_sep20 = mean_kurs_sep20.round(2)

kurs_aug20 = df3.loc[837:854, 'idr']
mean_kurs_aug20 = kurs_aug20.mean()
mk_aug20 = mean_kurs_aug20.round(2)

kurs_jul20 = df3.loc[855:876, 'idr']
mean_kurs_jul20 = kurs_jul20.mean()
mk_jul20 = mean_kurs_jul20.round(2)

kurs_jun20 = df3.loc[877:897, 'idr']
mean_kurs_jun20 = kurs_jun20.mean()
mk_jun20 = mean_kurs_jun20.round(2)

kurs_mei20 = df3.loc[898:913, 'idr']
mean_kurs_mei20 = kurs_mei20.mean()
mk_mei20 = mean_kurs_mei20.round(2)

kurs_apr20 = df3.loc[914:934, 'idr']
mean_kurs_apr20 = kurs_apr20.mean()
mk_apr20 = mean_kurs_apr20.round(2)

kurs_mar20 = df3.loc[935:955, 'idr']
mean_kurs_mar20 = kurs_mar20.mean()
mk_mar20 = mean_kurs_mar20.round(2)

kurs_feb20 = df3.loc[956:975, 'idr']
mean_kurs_feb20 = kurs_feb20.mean()
mk_feb20 = mean_kurs_feb20.round(2)

kurs_jan20 = df3.loc[976:998, 'idr']
mean_kurs_jan20 = kurs_jan20.mean()
mk_jan20 = mean_kurs_jan20.round(2)

data4 = {
    'Bulan' : ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],
    '2020' : [13721.26, 13766.95, 15178.95, 15710.52, 14854.69, 14105.33, 14529.91, 14649.17, 14785.0, 14686.32, 14184.05, 14094.47],
    '2021' : [14016.57, 14026.58, 14378.86, 14378.86, 14314.41, 14330.38, 14491.33, 14375.65, 14249.09, 14177.55, 14262.64, 14319.78],
    '2022' : [14335.19, 14345.78, 14344.82, 14373.05, 14616.47, 14699.14, 14977.0, 14839.09, 14983.09, 15433.43, 15656.78, 15597.36],
    '2023' : [15250.05, 15129.65, 15272.62, 14829.29, 14823.77, 14935.64, 15032.81, 15244.17, 15360.05, 15749.77, 15589.32, 15496.14]
}

df4 = pd.DataFrame(data4)
df4 = df4.set_index('Bulan')

plt.figure(figsize=(12, 6))
sns.set_style("whitegrid")

for col in df4.columns:
    plt.plot(df4.index, df4[col], marker='o', label=col)

plt.title('Nilai Tukar IDR terhadap USD')
plt.xlabel('Bulan')
plt.ylabel('Nilai')
plt.xticks(rotation=45)
plt.legend(title='Tahun')
plt.tight_layout()
plt.show()